version: '3'
services:
    need-proxy-image:
        image: ivories/redis:latest
        container_name: need-proxy-image
        restart: always
        depends_on:
            - redsocks
        network_mode: "service:ss-local"
    ss-local:
        image: ivories/shadowsocks-client
        container_name: ss-local
        restart: always
        cap_add:
            - NET_ADMIN
        environment:
            - PROXY_SERVER=123.1.2.3
            - PROXY_PORT=18080
            - PROXY_PASS=pass

