[parity]
chain = "ropsten"
mode = "active"
no_download = true


[rpc]
disable = false
port = 8545
interface = "all"
cors = []
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
hosts = ["none"]

